FROM node:20.13.1 AS base

RUN npm install -g pnpm@8

FROM base AS depencencies
WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --ignore-scripts

FROM base AS build
WORKDIR /usr/src/app
COPY . ./
COPY --from=depencencies /usr/src/app/node_modules ./node_modules
RUN pnpm run build
RUN pnpm prune --prod 

FROM node:20.13.1-alpine3.19 AS deploy
ARG DISCORD_TOKEN
ARG CLIENT_ID
ARG DISCORD_SERVER_ID
ARG DISCORD_CHANNEL
ARG DISCORD_PETDEX_ROLE
ARG DISCORD_OCTOPOST_ROLE
ARG DISCORD_OCTOPOST_CHANNEL
ARG DISCORD_PETDEX_CHANNEL
ARG CLASS_VIDEOS
ARG NOTION_TOKEN
ARG NOTION_DATABASE_ID

ENV DISCORD_TOKEN=$DISCORD_TOKEN
ENV CLIENT_ID=$CLIENT_ID
ENV DISCORD_SERVER_ID=$DISCORD_SERVER_ID
ENV DISCORD_CHANNEL=$DISCORD_CHANNEL
ENV DISCORD_PETDEX_ROLE=$DISCORD_PETDEX_ROLE
ENV DISCORD_OCTOPOST_ROLE=$DISCORD_OCTOPOST_ROLE
ENV DISCORD_OCTOPOST_CHANNEL=$DISCORD_OCTOPOST_CHANNEL
ENV DISCORD_PETDEX_CHANNEL=$DISCORD_PETDEX_CHANNEL
ENV CLASS_VIDEOS=$CLASS_VIDEOS
ENV NOTION_TOKEN=$NOTION_TOKEN
ENV NOTION_DATABASE_ID=$NOTION_DATABASE_ID

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package.json ./package.json

EXPOSE 3000

CMD ["node", "dist/main.js"]